<a href="https://colab.research.google.com/github/Willfan-R/Willfan.github.io/blob/master/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
class Pet(object):
    """Class object for a pet."""
  
    def __init__(self, species, name):
        """Initialize a Pet."""
        self.species = species
        self.name = name
 
    def __str__(self):
        """Output when printing an instance of a Pet."""
        return f"{self.species} named {self.name}"
        
    def change_name(self, new_name):
        """Change the name of your Pet."""
        self.name = new_name
        
my_dog = Pet(species="dog", 
             name="Scooby")
print (my_dog)
print (my_dog.name)
my_dog.change_name("moon")
print (my_dog.name)

dog named Scooby
Scooby
moon


In [0]:
import numpy as np
print ("np.eye((4)):\n", np.eye((4))) 
print ("np.zeros((3)):\n", np.zeros((2,2,2,2))) 
#print ("np.zeros((imags zero)):\n", np.zeros((4,4,3,1))) 
#print ("np.zeros((imags one)):\n", np.ones((4,4,3,1))) 
img0 = np.zeros((4,4,3,1))
img1 = np.ones((4,4,3,1))
np.concatenate((img0,img1),axis=3)

np.eye((4)):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
np.zeros((3)):
 [[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


array([[[[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]]],


       [[[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]]],


       [[[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]]],


       [[[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]]]])

In [0]:
# axis 0,1


# Sum across a dimension
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum axis=0: ", np.sum(x, axis=0)) # sum across rows
print ("sum axis=1: ", np.sum(x, axis=1)) # sum across columns

[[1 2]
 [3 4]]
sum all:  10
sum axis=0:  [4 6]
sum axis=1:  [3 7]


In [0]:
# Removing dimensions
x = np.array([[[1,2,3]],[[4,5,6]]])
x1 = np.array([[1,2,3],[4,5,6]])
print ("x1.shape: ", x1.shape)
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.squeeze(x, 1) # squeeze dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)  # notice extra set of brackets are gone

x1.shape:  (2, 3)
x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)


In [0]:
import pandas as pd
import urllib
np.random.seed(seed=1234)
url = 'https://raw.githubusercontent.com/madewithml/lessons/master/data/titanic.csv'
response = urllib.request.urlopen(url)
html = response.read()
with open('titanic.csv', 'wb') as f:
    f.write(html)
!ls -l


total 88
drwxr-xr-x 1 root root  4096 Mar 18 16:23 sample_data
-rw-r--r-- 1 root root 85153 Mar 26 07:25 titanic.csv


In [0]:
df = pd.read_csv("titanic.csv",header=0)
df.head()

pclass                                             name  ... embarked  survived
0       1                    Allen, Miss. Elisabeth Walton  ...        S         1
1       1                   Allison, Master. Hudson Trevor  ...        S         1
2       1                     Allison, Miss. Helen Loraine  ...        S         0
3       1             Allison, Mr. Hudson Joshua Creighton  ...        S         0
4       1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  ...        S         0

[5 rows x 11 columns]

In [0]:
df1 = pd.read_csv("titanic.csv",header=1)
df1.head()
print(help(df.describe()))

NameError: ignored

In [0]:
import math
print(math.pow(100,10))
print(1.1**7)

1e+20
1.9487171000000012


In [0]:
import tensorflow as tf
import cv2 
img = cv2.imread("test_img_1.png")
print(img.shape)
print(img)

imgResize = cv2.resize(img,(32,32))
print("=====================")
print(imgResize.shape)
print(imgResize)


(148, 148, 3)
[[[182 137  80]
  [182 137  80]
  [182 137  80]
  ...
  [173 131  84]
  [173 131  84]
  [173 131  84]]

 [[182 137  80]
  [182 137  80]
  [182 137  80]
  ...
  [173 131  84]
  [173 131  84]
  [173 131  84]]

 [[182 137  80]
  [182 137  80]
  [182 137  80]
  ...
  [173 131  84]
  [173 131  84]
  [173 131  84]]

 ...

 [[217 188 144]
  [217 188 144]
  [217 188 144]
  ...
  [222 184 149]
  [222 184 149]
  [222 184 149]]

 [[217 188 144]
  [217 188 144]
  [217 188 144]
  ...
  [222 184 149]
  [222 184 149]
  [222 184 149]]

 [[217 188 144]
  [217 188 144]
  [217 188 144]
  ...
  [222 184 149]
  [222 184 149]
  [222 184 149]]]
(32, 32, 3)
[[[182 137  80]
  [184 137  84]
  [188 141  87]
  ...
  [187 136  86]
  [178 132  85]
  [173 131  84]]

 [[185 139  85]
  [188 141  87]
  [190 143  89]
  ...
  [191 141  89]
  [183 136  88]
  [178 134  87]]

 [[188 140  88]
  [189 141  89]
  [192 145  91]
  ...
  [191 144  90]
  [188 141  90]
  [183 138  87]]

 ...

 [[224 187 137]
  [226 188

In [0]:
print("===================== addAxis")
imgaddAxis = imgResize[:,:,:,np.newaxis]
imgaddAxis


===================== addAxis


array([[[[182],
         [137],
         [ 80]],

        [[184],
         [137],
         [ 84]],

        [[188],
         [141],
         [ 87]],

        ...,

        [[187],
         [136],
         [ 86]],

        [[178],
         [132],
         [ 85]],

        [[173],
         [131],
         [ 84]]],


       [[[185],
         [139],
         [ 85]],

        [[188],
         [141],
         [ 87]],

        [[190],
         [143],
         [ 89]],

        ...,

        [[191],
         [141],
         [ 89]],

        [[183],
         [136],
         [ 88]],

        [[178],
         [134],
         [ 87]]],


       [[[188],
         [140],
         [ 88]],

        [[189],
         [141],
         [ 89]],

        [[192],
         [145],
         [ 91]],

        ...,

        [[191],
         [144],
         [ 90]],

        [[188],
         [141],
         [ 90]],

        [[183],
         [138],
         [ 87]]],


       ...,


       [[[224],
         [187],
      

In [0]:
imgs = np.zeros([32,32,3,1])


NameError: ignored

In [0]:
imgSum = np.concatenate((imgs,imgaddAxis),axis=3)
imgSum = imgSum.astype(np.float32)/255.
imgSum 

NameError: ignored

In [0]:
import pandas as pd
import numpy as np
from numpy import nan as NA

obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj.drop('c')
randomdata = np.random.randn(7,3)
df = pd.DataFrame(randomdata)
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
print(df)
df1 = df.dropna()
df1

arr = np.array([
    [1, 2, 3, 4],
    [2, 4, 6, 8],
    [3, 6, 9, 12],
    [4, 8, 12, 16]
])
arr

          0         1         2
0 -0.919720       NaN       NaN
1  0.893021       NaN       NaN
2  0.917380       NaN -1.211138
3 -2.899877       NaN  0.623915
4  0.381910 -2.986009  0.428994
5  1.502329 -0.102162  0.008371
6  0.778272  1.512410  0.112049


In [0]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [2, 4, 6, 8],
    [3, 6, 9, 12],
    [4, 8, 12, 16]
])
arr

print(arr[[0, 2], [3, 1]])

[4 6]
